name: tasking
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.9
  flutter_riverpod: ^1.0.3
  intl: ^0.17.0
  path: ^1.8.0
  sqflite: ^2.0.2
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  sqflite_common_ffi: ^2.1.0+2

flutter:
  uses-material-design: true
